general:
  complete_verifier: skip
model:
  onnx_path: ../saved_models/mnist_fcnn.onnx
data:
  dataset: MNIST
  start: 0
  end: 100
specification:
  norm: .inf
  epsilon: 0.03
attack:
  pgd_order: skip
solver:
  batch_size: 1024
  bound_prop_method: crown
bab:
  timeout: 30
