general:
  complete_verifier: skip
model:
  onnx_path: ../saved_models/mnist_fcnn.onnx
data:
  dataset: MNIST
  start: 0
  end: 100
specification:
  norm: .inf
  epsilon: 0.01
attack:
  pgd_order: skip
solver:
  batch_size: 1024
  bound_prop_method: alpha-crown
  alpha-crown:
    iteration: 100
    lr_alpha: 0.1
bab:
  timeout: 30
