general:
  complete_verifier: skip
model:
  name: cifar_marabou_small
  path: models/marabou_cifar10/cifar_marabou_small.pth
data:
  dataset: CIFAR
  std: 1.0
  mean: 0.0
  start: 0
  end: 20
specification:
  norm: .inf
  epsilon: 0.00784313725  # 2/255
attack:
  pgd_order: skip
solver:
  batch_size: 1024
  bound_prop_method: crown
bab:
  timeout: 120
